export const ACTIONS = {
	TOGGLE_SONG: 'TOGGLE_SONG',
	NEXT_SONG: 'NEXT_SONG',
	PREV_SONG: 'PREV_SONG',
	LOOP_SONG: 'LOOP_SONG',
	RANDOM_SONG: 'RANDOM_SONG',
	CHANGE_VOLUME: 'CHANGE_VOLUME',
	OPEN_LIST: 'OPEN_LIST',
};
